version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/native/candlex"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
