name: NIF binaries

on:
  push:
    branches:
      - main
    paths:
      - "native/**"
      - ".github/workflows/binaries.yml"
    tags:
      - "*"
  pull_request:
    paths:
      - ".github/workflows/binaries.yml"
  workflow_dispatch:

jobs:
  build_binary:
    name: ${{ matrix.target }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        - target: aarch64-apple-darwin
          os: macos-12
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-22.04
          use-cross: true
        - target: x86_64-apple-darwin
          os: macos-12
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-22.04
    env:
      VERSION: "0.1.2"

    steps:
      - uses: actions/checkout@v4
      - run: rustup target add ${{ matrix.target }}

      - uses: philss/rustler-precompiled-action@main
        id: precompile
        with:
          project-dir: "native/candlex"
          project-name: candlex
          project-version: ${{ env.VERSION }}
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          nif-version: "2.16"

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ steps.precompile.outputs.file-path }}
        if: startsWith(github.ref, 'refs/tags/')
