name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CANDLEX_NIF_BUILD: true
      BLEND: ${{ matrix.blend }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir_version: 1.16.0
            otp_version: '26.2.1'
            lint: true
          - elixir_version: 1.15.7
            otp_version: '25.3.2.8'
          - elixir_version: 1.15.7
            otp_version: '25.3.2.8'
            blend: "bumblebee03"
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check --manifest-path=native/candlex/Cargo.toml
        if: ${{ matrix.lint }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_version}}
          elixir-version: ${{matrix.elixir_version}}
      - run: mix deps.unlock --all && mix deps.get
        if: ${{ github.event_name == 'schedule' }}
      - run: mix deps.get --check-locked
        if: ${{ github.event_name != 'schedule' }}
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - run: mix test
      - run: mix run examples/linear_regression.exs
      - run: mix run examples/image_classification.exs
      - run: mix run examples/text_classification.exs
