name: CI
on:
  pull_request:
  push:
  schedule:
    - cron: '0 12 1 * *'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CANDLEX_NIF_BUILD: true
      BLEND: ${{ matrix.blend }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.18'
            erlang: '27.2'
            lint: true
          - elixir: '1.17'
            erlang: '26.2.5.6'
          - elixir: '1.16'
            erlang: '25.3.2.16'
          - elixir: '1.15'
            erlang: '25.3.2.16'
          - elixir: '1.15'
            erlang: '25.3.2.16'
            blend: "nx07"
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check --manifest-path=native/candlex/Cargo.toml
        if: ${{ matrix.lint }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.unlock --all && mix deps.get
        if: ${{ github.event_name == 'schedule' }}
      - run: mix deps.get --check-locked
        if: ${{ github.event_name != 'schedule' }}
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - run: mix test
      - run: mix run examples/linear_regression.exs
      - run: mix run examples/image_classification.exs
      - run: mix run examples/text_classification.exs
